"""update_user_model

Revision ID: 961eedae25c0
Revises: 0003_auth_additions
Create Date: 2026-08-25 19:58:02.726869
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '961eedae25c0'
down_revision: str | None = '0003_auth_additions'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('first_name', sa.String(length=100), nullable=False))
    op.add_column('users', sa.Column('last_name', sa.String(length=100), nullable=False))
    op.add_column('users', sa.Column('google_id', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('avatar_url', sa.String(length=255), nullable=True))
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
    op.drop_column('users', 'username')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.VARCHAR(length=150), nullable=False))
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=1)
    op.drop_column('users', 'avatar_url')
    op.drop_column('users', 'google_id')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    # ### end Alembic commands ###
